/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View.MainNavigation;

//Appointment form imports
import View.MainNavigation.Appointment.ViewAppointment;
import View.MainNavigation.Appointment.NewAppointment;
import View.MainNavigation.Appointment.NewAppointment;
import View.MainNavigation.Appointment.EditAppointment;
import View.MainNavigation.Appointment.ViewAppointment;
// Counsellor form imports
import View.CounselorForm;
//These imports aren't necessary
//import View.MainNavigation.Counsellor.NewCounsellor;
//import View.MainNavigation.Counsellor.ViewCounsellor;
//import View.MainNavigation.Counsellor.EditCounsellor;
// Feedback form imports
import View.MainNavigation.Feedback.NewFeedback;
import View.MainNavigation.Feedback.ViewFeedback;
import View.MainNavigation.Feedback.EditFeedback;





public class MainNavigation extends javax.swing.JFrame {
    public MainNavigation() {
        initComponents();
     
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainNavigation.class.getName());


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TabNavigation = new javax.swing.JTabbedPane();
        plAppointmentsMain = new javax.swing.JPanel();
        btnNewAppointment = new javax.swing.JButton();
        btnEditAppointment = new javax.swing.JButton();
        btnViewAppointments = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        plCounsellorsMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnViewCounsellors = new javax.swing.JButton();
        btnEditCounsellor = new javax.swing.JButton();
        btnNewCounsellor = new javax.swing.JButton();
        plFeedbackMain = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnViewFeedback = new javax.swing.JButton();
        btnEditFeedback = new javax.swing.JButton();
        btnNewFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Main Navigation");

        TabNavigation.setRequestFocusEnabled(false);

        plAppointmentsMain.setBackground(new java.awt.Color(255, 204, 204));
        plAppointmentsMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        btnNewAppointment.setText("New Appointment");
        btnNewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAppointment(evt);
            }
        });

        btnEditAppointment.setText("Edit Appointment");
        btnEditAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAppointment(evt);
            }
        });

        btnViewAppointments.setText("View Appointments");
        btnViewAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAppointments(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Make a new appointment:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Edit an existing appointment:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("View all appointments:");

        javax.swing.GroupLayout plAppointmentsMainLayout = new javax.swing.GroupLayout(plAppointmentsMain);
        plAppointmentsMain.setLayout(plAppointmentsMainLayout);
        plAppointmentsMainLayout.setHorizontalGroup(
            plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plAppointmentsMainLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(185, 185, 185))
        );
        plAppointmentsMainLayout.setVerticalGroup(
            plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plAppointmentsMainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewAppointment)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63)
                .addGroup(plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditAppointment)
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addGroup(plAppointmentsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAppointments)
                    .addComponent(jLabel5))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        TabNavigation.addTab("Appointments", plAppointmentsMain);

        plCounsellorsMain.setBackground(new java.awt.Color(204, 255, 204));
        plCounsellorsMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 2));
        plCounsellorsMain.setForeground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Register a new counsellor:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Edit an existing counsellor:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("View all counsellors:");

        btnViewCounsellors.setText("View counsellors");
        btnViewCounsellors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCounsellor(evt);
            }
        });

        btnEditCounsellor.setText("Edit Counsellor");
        btnEditCounsellor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCounsellor(evt);
            }
        });

        btnNewCounsellor.setText("New Counsellor");
        btnNewCounsellor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCounsellor(evt);
            }
        });

        javax.swing.GroupLayout plCounsellorsMainLayout = new javax.swing.GroupLayout(plCounsellorsMain);
        plCounsellorsMain.setLayout(plCounsellorsMainLayout);
        plCounsellorsMainLayout.setHorizontalGroup(
            plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plCounsellorsMainLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCounsellors, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCounsellor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewCounsellor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(185, 185, 185))
        );
        plCounsellorsMainLayout.setVerticalGroup(
            plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plCounsellorsMainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewCounsellor)
                    .addComponent(jLabel6))
                .addGap(63, 63, 63)
                .addGroup(plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditCounsellor)
                    .addComponent(jLabel7))
                .addGap(64, 64, 64)
                .addGroup(plCounsellorsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCounsellors)
                    .addComponent(jLabel8))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        TabNavigation.addTab("Counsellors", plCounsellorsMain);

        plFeedbackMain.setBackground(new java.awt.Color(204, 255, 255));
        plFeedbackMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Submit new feedback:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Edit existing feedback:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("View all feedback:");

        btnViewFeedback.setText("View feedback");
        btnViewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFeedback(evt);
            }
        });

        btnEditFeedback.setText("Edit feedback");
        btnEditFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFeedback(evt);
            }
        });

        btnNewFeedback.setText("New feedback");
        btnNewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFeedback(evt);
            }
        });

        javax.swing.GroupLayout plFeedbackMainLayout = new javax.swing.GroupLayout(plFeedbackMain);
        plFeedbackMain.setLayout(plFeedbackMainLayout);
        plFeedbackMainLayout.setHorizontalGroup(
            plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plFeedbackMainLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(121, 121, 121)
                .addGroup(plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        plFeedbackMainLayout.setVerticalGroup(
            plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plFeedbackMainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewFeedback)
                    .addComponent(jLabel9))
                .addGap(63, 63, 63)
                .addGroup(plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditFeedback)
                    .addComponent(jLabel10))
                .addGap(64, 64, 64)
                .addGroup(plFeedbackMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewFeedback)
                    .addComponent(jLabel11))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        TabNavigation.addTab("Feedback", plFeedbackMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(TabNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TabNavigation.getAccessibleContext().setAccessibleParent(TabNavigation);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewFeedback(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFeedback
        NewFeedback form = new NewFeedback();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_NewFeedback

    private void EditFeedback(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFeedback
        EditFeedback form = new EditFeedback();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_EditFeedback

    private void ViewFeedback(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFeedback
        ViewFeedback form = new ViewFeedback();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ViewFeedback

    private void NewCounsellor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCounsellor
        CounselorForm form = new CounselorForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_NewCounsellor

    private void EditCounsellor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCounsellor
        CounselorForm form = new CounselorForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_EditCounsellor

    //Counsellor actions for buttons to navigate to respective forms
    private void ViewCounsellor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCounsellor
        CounselorForm form = new CounselorForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ViewCounsellor

    private void ViewAppointments(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAppointments
        ViewAppointment form = new ViewAppointment();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ViewAppointments

    private void EditAppointment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAppointment
        EditAppointment form = new EditAppointment();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_EditAppointment

    //Appointment actions for buttons to navigate to respective forms
    private void NewAppointment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAppointment
        NewAppointment form = new NewAppointment();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_NewAppointment


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainNavigation().setVisible(true));      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabNavigation;
    private javax.swing.JButton btnEditAppointment;
    private javax.swing.JButton btnEditCounsellor;
    private javax.swing.JButton btnEditFeedback;
    private javax.swing.JButton btnNewAppointment;
    private javax.swing.JButton btnNewCounsellor;
    private javax.swing.JButton btnNewFeedback;
    private javax.swing.JButton btnViewAppointments;
    private javax.swing.JButton btnViewCounsellors;
    private javax.swing.JButton btnViewFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel plAppointmentsMain;
    private javax.swing.JPanel plCounsellorsMain;
    private javax.swing.JPanel plFeedbackMain;
    // End of variables declaration//GEN-END:variables
}






