package View.MainNavigation.Feedback;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import View.MainNavigation.MainNavigation;


import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER-PC
 */
public class NewFeedback extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewFeedback.class.getName());

    private static class Feedback {
        String name;
        String surname;
        int studentId;
        String comment;
        int rating;

    public Feedback(String name, String surname, int studentId, String comment, int rating) {
        this.name = name;
        this.surname = surname;
        this.studentId = studentId;
        this.comment = comment;
        this.rating = rating;
    }
}
    private java.util.List<Feedback> feedbackList = new java.util.ArrayList<>();
    /**
     * Creates new form NewFeedback
     */
    public NewFeedback() {
        initComponents();

        // Set the table model first
        tbFeedbackDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                // start empty
            },
            new String [] {
                "Name", "Surname", "ID", "Rating", "Feedback"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
        }
    });

    // Add predefined feedback entries
    feedbackList.add(new Feedback("Alice", "Smith", 1001, "Great session, very helpful!", 5));
    feedbackList.add(new Feedback("Bob", "Johnson", 1002, "Could use more detailed advice.", 3));
    feedbackList.add(new Feedback("Carla", "Brown", 1003, "Felt heard and understood.", 4));
    feedbackList.add(new Feedback("Daniel", "Lee", 1004, "Very professional.", 5));
    feedbackList.add(new Feedback("Eva", "Martinez", 1005, "It was okay, a bit rushed.", 3));
    feedbackList.add(new Feedback("Frank", "White", 1006, "I didn't get much value.", 2));
    feedbackList.add(new Feedback("Grace", "Kim", 1007, "Amazing experience!", 5));
    feedbackList.add(new Feedback("Hassan", "Nguyen", 1008, "Neutral feelings.", 3));
    feedbackList.add(new Feedback("Ivy", "Singh", 1009, "Felt comfortable opening up.", 4));
    feedbackList.add(new Feedback("Jake", "Muller", 1010, "Wish I had more time.", 3));

    // Now refresh the table to display feedbackList
    refreshTable();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ReturnMain1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFeedback = new javax.swing.JTextArea();
        tfFeedbackName = new javax.swing.JTextField();
        tfFeedbackSurname = new javax.swing.JTextField();
        tfFeedbackID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnFeedbackClear = new javax.swing.JButton();
        btnFeedbackSubmit = new javax.swing.JButton();
        spinRate = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFeedbackDisplay = new javax.swing.JTable();
        btnDeleteFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Feedback Management");

        ReturnMain1.setText("Return Main");
        ReturnMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnMain(evt);
            }
        });

        jLabel2.setText("Enter Name:");

        jLabel3.setText("Enter Surname:");

        jLabel4.setText("Enter ID:");

        jLabel5.setText("Enter feedback:");

        taFeedback.setColumns(20);
        taFeedback.setRows(5);
        taFeedback.setText("Feeeeedback (500 character cap?)");
        jScrollPane1.setViewportView(taFeedback);

        tfFeedbackName.setText("Enter a name");

        tfFeedbackSurname.setText("Enter a surname");

        tfFeedbackID.setText("Enter a ID");

        jLabel6.setText("Please rate our service:");

        btnFeedbackClear.setText("Clear");
        btnFeedbackClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFeedback(evt);
            }
        });

        btnFeedbackSubmit.setText("Submit");
        btnFeedbackSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitFeedback(evt);
            }
        });

        spinRate.setModel(new javax.swing.SpinnerNumberModel(5, 1, 5, 1));

        tbFeedbackDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "ID", "Rating", "Feedback"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbFeedbackDisplay);

        btnDeleteFeedback.setText("Delete entry");
        btnDeleteFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEntry(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteFeedback)
                        .addGap(56, 56, 56)
                        .addComponent(ReturnMain1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFeedbackClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnFeedbackSubmit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfFeedbackID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfFeedbackSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfFeedbackName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(57, 70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfFeedbackName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFeedbackSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfFeedbackID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spinRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFeedbackSubmit)
                    .addComponent(btnFeedbackClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnMain1)
                    .addComponent(btnDeleteFeedback))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tbFeedbackDisplay.getModel();
        model.setRowCount(0); // Clear all existing rows
        for (Feedback fb : feedbackList) {
            model.addRow(new Object[]{fb.name, fb.surname, fb.studentId, fb.rating, fb.comment});
        }
    }
    
    private void addFeedbackToTable(Feedback fb) {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tbFeedbackDisplay.getModel();
    model.addRow(new Object[]{fb.name, fb.surname, fb.studentId, fb.rating, fb.comment});
}

    private void clearForm() {
        tfFeedbackName.setText("");
        tfFeedbackSurname.setText("");
        tfFeedbackID.setText("");
        taFeedback.setText("");
        spinRate.setValue(1);
}
    
    private void ReturnMain(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnMain
        MainNavigation mainForm = new MainNavigation();
        mainForm.setVisible(true);
        mainForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ReturnMain

    private void btnClearFeedback(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFeedback
        clearForm();
    }//GEN-LAST:event_btnClearFeedback
  
    private void btnSubmitFeedback(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFeedback
        String name = tfFeedbackName.getText().trim();
        String surname = tfFeedbackSurname.getText().trim();
        String idText = tfFeedbackID.getText().trim();
        String comment = taFeedback.getText().trim();
        int rating = (int) spinRate.getValue();

        if (name.isEmpty() || surname.isEmpty() || idText.isEmpty() || comment.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        int studentId;
        try {
            studentId = Integer.parseInt(idText);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid student ID.");
            return;
        }
    
        // Check for duplicate ID before adding
        for (Feedback fb : feedbackList) {
            if (fb.studentId == studentId) {
                javax.swing.JOptionPane.showMessageDialog(this, "Student ID already exists. Please enter a unique ID.");
                return;  // Stop adding duplicate
            }
        }

    Feedback fb = new Feedback(name, surname, studentId, comment, rating);
    feedbackList.add(fb);
    addFeedbackToTable(fb);
    javax.swing.JOptionPane.showMessageDialog(this, "Feedback submitted successfully!");
    clearForm();
    }//GEN-LAST:event_btnSubmitFeedback

    private void btnDeleteEntry(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEntry
        int selectedRow = tbFeedbackDisplay.getSelectedRow();
        System.out.println("Selected Row: " + selectedRow);
        if (selectedRow >= 0) {
            feedbackList.remove(selectedRow);
            refreshTable();
          JOptionPane.showMessageDialog(this, "Entry deleted.");
        } else {
         JOptionPane.showMessageDialog(this, "Please select a feedback entry to delete.");
        }
    
    }//GEN-LAST:event_btnDeleteEntry

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnMain1;
    private javax.swing.JButton btnDeleteFeedback;
    private javax.swing.JButton btnFeedbackClear;
    private javax.swing.JButton btnFeedbackSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinRate;
    private javax.swing.JTextArea taFeedback;
    private javax.swing.JTable tbFeedbackDisplay;
    private javax.swing.JTextField tfFeedbackID;
    private javax.swing.JTextField tfFeedbackName;
    private javax.swing.JTextField tfFeedbackSurname;
    // End of variables declaration//GEN-END:variables
}
